#!/usr/bin/env python3
"""Export a draft LLVM schedule model from generated RVV profiles."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import search_model


LMUL_ORDER = ("m1", "m2", "m4")
RESOURCE_DEFS = (
    "YuShuXinVPipe0",
    "YuShuXinVPipe1",
    "YuShuXinAnyVPipe",
)


def nested_get(data: dict[str, Any], path: tuple[str, ...]) -> Any:
    current: Any = data
    for part in path:
        if not isinstance(current, dict):
            return None
        current = current.get(part)
    return current


def int_or_none(value: Any) -> int | None:
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float) and value.is_integer():
        return int(value)
    if isinstance(value, str):
        try:
            return int(value, 0)
        except ValueError:
            return None
    return None


def load_profiles(root: Path) -> list[tuple[Path, dict[str, Any]]]:
    return search_model.load_profiles([root.as_posix()])


def tablegen_identifier(text: Any) -> str:
    raw = str(text or "Unknown")
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in raw)


def evidence_text(record: Any) -> str:
    if not isinstance(record, dict):
        return "none"
    evidence = record.get("evidence")
    if isinstance(evidence, list) and evidence:
        return "; ".join(str(item) for item in evidence)
    return "none"


def measurement_rows(profile_path: Path, profile: dict[str, Any]) -> list[dict[str, Any]]:
    instr = nested_get(profile, ("instruction", "id"))
    asm = nested_get(profile, ("instruction", "asm"))
    sched_write = nested_get(profile, ("instruction", "llvm_sched_write")) or instr
    measurements = profile.get("measurements")
    if not isinstance(measurements, dict):
        return []
    rows: list[dict[str, Any]] = []
    for lmul in LMUL_ORDER:
        measurement = measurements.get(lmul)
        if not isinstance(measurement, dict):
            continue
        latency_record = nested_get(measurement, ("llvm", "latency"))
        release_record = nested_get(measurement, ("llvm", "release_at_cycles"))
        resource_record = nested_get(measurement, ("llvm", "resource_group"))
        num_micro_ops_record = nested_get(measurement, ("llvm", "num_micro_ops"))
        single_issue_record = nested_get(measurement, ("llvm", "single_issue"))
        latency = int_or_none(latency_record.get("value") if isinstance(latency_record, dict) else None)
        release = int_or_none(release_record.get("value") if isinstance(release_record, dict) else None)
        resource = resource_record.get("value") if isinstance(resource_record, dict) else None
        if latency is None or release is None or resource is None:
            continue
        rows.append(
            {
                "profile": profile_path.as_posix(),
                "instruction": instr,
                "asm": asm,
                "sched_write": sched_write,
                "lmul": lmul,
                "latency": latency,
                "release": release,
                "resource": resource,
                "num_micro_ops": num_micro_ops_record if isinstance(num_micro_ops_record, dict) else {},
                "single_issue": single_issue_record if isinstance(single_issue_record, dict) else {},
                "evidence": evidence_text(latency_record),
            }
        )
    return rows


def build_rows(profiles: list[tuple[Path, dict[str, Any]]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for profile_path, profile in profiles:
        rows.extend(measurement_rows(profile_path, profile))
    return sorted(rows, key=lambda row: (str(row["instruction"]), LMUL_ORDER.index(row["lmul"])))


def render_tablegen(rows: list[dict[str, Any]]) -> str:
    lines = [
        "// Generated by scripts/export_llvm_draft.py.",
        "// Source: profile_inst_latency generated profile.yaml evidence.",
        "// Draft only: review resource naming and instruction-to-LMUL plumbing before LLVM import.",
        "",
        "def YuShuXinModel : SchedMachineModel {",
        "  let IssueWidth = 2;",
        "  let MicroOpBufferSize = 0;",
        "  let LoadLatency = 0;",
        "}",
        "",
        "def YuShuXinVPipe0 : ProcResource<1>;",
        "def YuShuXinVPipe1 : ProcResource<1>;",
        "def YuShuXinAnyVPipe : ProcResGroup<[YuShuXinVPipe0, YuShuXinVPipe1]>;",
        "",
    ]
    emitted: set[str] = set()
    for row in rows:
        sched_write = tablegen_identifier(row["sched_write"])
        lmul_suffix = row["lmul"].upper()
        def_name = f"YuShuXin{sched_write}_{lmul_suffix}"
        if def_name in emitted:
            continue
        emitted.add(def_name)
        resource = row["resource"]
        if resource not in RESOURCE_DEFS:
            resource = tablegen_identifier(resource)
        lines.append(f"// Evidence: {row['evidence']}")
        lines.append(f"def {def_name} : SchedWriteRes<[{resource}]> {{")
        lines.append(f"  let Latency = {row['latency']};")
        lines.append(f"  let ReleaseAtCycles = [{row['release']}];")
        num_record = row["num_micro_ops"]
        if isinstance(num_record, dict) and num_record.get("claimed"):
            num_micro_ops = int_or_none(num_record.get("value"))
            if num_micro_ops is not None:
                lines.append(f"  let NumMicroOps = {num_micro_ops};")
        else:
            lines.append("  // NumMicroOps is recorded in the profile but not claimed by current evidence.")
        single_record = row["single_issue"]
        if isinstance(single_record, dict) and single_record.get("claimed") and single_record.get("value"):
            lines.append("  let SingleIssue = true;")
        else:
            lines.append("  // SingleIssue is recorded in the profile but not claimed by current evidence.")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def render_mapping(rows: list[dict[str, Any]]) -> str:
    lines = [
        "# YuShuXin LLVM Model Mapping",
        "",
        "Status: generated_from_profile_evidence",
        "",
        "The TableGen draft is generated from `results/<instruction>/profile.yaml`. Latency, ReleaseAtCycles, and resource fields below come from synthetic trace evidence; unclaimed fields remain comments in the draft.",
        "",
        "## Instruction/LMUL Mapping",
        "",
        "| Instruction | ASM | LMUL | SchedWrite def | Resource | Latency | ReleaseAtCycles | Evidence |",
        "| --- | --- | --- | --- | --- | ---: | ---: | --- |",
    ]
    for row in rows:
        sched_write = tablegen_identifier(row["sched_write"])
        def_name = f"YuShuXin{sched_write}_{row['lmul'].upper()}"
        lines.append(
            f"| `{row['instruction']}` | `{row['asm']}` | `{row['lmul']}` | `{def_name}` | "
            f"`{row['resource']}` | {row['latency']} | {row['release']} | `{row['evidence']}` |"
        )

    lines.extend(["", "## Non-Claims", ""])
    lines.append("- `NumMicroOps` is not emitted unless a profile marks it as claimed.")
    lines.append("- `SingleIssue` is not emitted unless a profile marks it as claimed.")
    lines.append("- `ReadAdvance` and physical writeback latency are not generated from current synthetic evidence.")
    lines.append("- The draft uses per-LMUL write definitions so LMUL-dependent latency/release values are not collapsed into placeholders.")
    return "\n".join(lines) + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export LLVM schedule draft from generated profiles.")
    parser.add_argument("--profile-root", default="results", help="Root containing results/<instruction>/profile.yaml")
    parser.add_argument("--td-output", default="results/common/llvm_model_draft.td")
    parser.add_argument("--mapping-output", default="results/common/llvm_model_mapping.md")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    profiles = load_profiles(Path(args.profile_root))
    rows = build_rows(profiles)
    if not rows:
        print(f"FAIL: no profile evidence found under {args.profile_root}")
        return 1

    td_path = Path(args.td_output)
    mapping_path = Path(args.mapping_output)
    td_path.parent.mkdir(parents=True, exist_ok=True)
    mapping_path.parent.mkdir(parents=True, exist_ok=True)
    td_path.write_text(render_tablegen(rows), encoding="utf-8")
    mapping_path.write_text(render_mapping(rows), encoding="utf-8")
    print(f"wrote {td_path}")
    print(f"wrote {mapping_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
